version: '{build}'
configuration: Release
platform: x86
image:
- Visual Studio 2017
clone_folder: C:\projects\src\Windows-Frotz
install:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
- cmd: cd c:\projects\
- cmd: IF NOT EXIST c:\projects\Libraries\ git clone https://github.com/DavidKinder/Libraries.git
- cmd: IF NOT EXIST c:\projects\Libraries\zlib appveyor DownloadFile https://zlib.net/zlib1211.zip
- cmd: IF NOT EXIST c:\projects\Libraries\zlib 7z x zlib1211.zip -oc:\projects\Libraries
- cmd: IF NOT EXIST c:\projects\Libraries\zlib ren c:\projects\Libraries\zlib-1.2.11 zlib
- cmd: IF NOT EXIST c:\projects\Libraries\libvorbis appveyor DownloadFile http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.zip
- cmd: IF NOT EXIST c:\projects\Libraries\libvorbis 7z x libvorbis-1.3.6.zip -oc:\projects\Libraries
- cmd: IF NOT EXIST c:\projects\Libraries\libvorbis ren c:\projects\Libraries\libvorbis-1.3.6 libvorbis
- cmd: IF NOT EXIST c:\projects\Libraries\libogg appveyor DownloadFile http://downloads.xiph.org/releases/ogg/libogg-1.3.3.zip
- cmd: IF NOT EXIST c:\projects\Libraries\libogg 7z x libogg-1.3.3.zip -oc:\projects\Libraries
- cmd: IF NOT EXIST c:\projects\Libraries\libogg ren c:\projects\Libraries\libogg-1.3.3 libogg
- cmd: IF NOT EXIST c:\projects\Libraries\libpng appveyor DownloadFile https://sourceforge.net/projects/libpng/files/libpng16/1.6.37/lpng1637.zip
- cmd: IF NOT EXIST c:\projects\Libraries\libpng 7z x lpng1637.zip -oc:\projects\Libraries
- cmd: IF NOT EXIST c:\projects\Libraries\libpng ren c:\projects\Libraries\lpng1637 libpng
- cmd: IF NOT EXIST c:\projects\Libraries\libpng\pnglibconf.h grep -v PNG_SAVE_ c:\projects\Libraries\libpng\scripts\pnglibconf.h.prebuilt | grep -v PNG_WRITE_ | grep -v PNG_SIMPLIFIED_WRITE_ > c:\projects\Libraries\libpng\pnglibconf.h
- cmd: IF NOT EXIST c:\projects\Libraries\jpeg appveyor DownloadFile https://www.ijg.org/files/jpegsr9c.zip
- cmd: IF NOT EXIST c:\projects\Libraries\jpeg 7z x jpegsr9c.zip -oc:\projects\Libraries
- cmd: IF NOT EXIST c:\projects\Libraries\jpeg ren c:\projects\Libraries\jpeg-9c jpeg
- cmd: IF NOT EXIST c:\projects\Libraries\jpeg\jconfig.h ren c:\projects\Libraries\jpeg\jconfig.vc jconfig.h
- cmd: cd C:\projects\src\Windows-Frotz\Win
cache:
  - c:\projects\Libraries
before_build:
- cmd: devenv Frotz.sln /Upgrade
build_script:
- cmd: msbuild Frotz.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
- cmd: cd Release
- cmd: 7z a Frotz.zip Frotz.exe Frotz.chm *.dll
artifacts:
  - path: Win/Release/Frotz.exe
  - path: Win/Release/Frotz.zip

